'''Fitness function for NEAT using Lenia.'''
###################################################################################
''' imports '''

import numpy as np
import time
###################################################################################
''' custom imports '''
import Lenia.lenia_factory as factory
import Lenia.lenia_env as env
import Lenia.lenia_data_manager as manager

import Lenia.EExamples.aquarium as aquarium

import Lenia.Functions.Math as math
###################################################################################
''' fitness function '''

''' Structure of the fitness function, you can adjust the desired fitness by changing which mathematical function to call'''
def fitness_main(configuration): # configuration is the result of a pattern generated by NEAT it should be of the settings size
    
    manager.clear_dataout_folder()
    
    # necessary parameters for Lenia
    tag = str("configuration_gen_" + time.strftime("%Y%m%d-%H%M%S"))
    r = aquarium.pattern["aquarium"]['R']
    t = aquarium.pattern["aquarium"]['T']
    kernels = aquarium.pattern["aquarium"]['kernels']
    cells = configuration
    
    singleton = factory.entity_creator(tag, r, t, kernels, cells)
    env.run_world_execute(singleton, show_animation=True, max_iterations=2000)
    data = manager.get_frames()
    
    ''' Data is the Lenia output array, shape is (frames, x, y, channels).'''
    # fit = fitness_SR(data)
    fit = fitness_entropy(data)
    print("Fitness at " + time.strftime("%Y%m%d-%H%M%S") + ":", fit)
    return fit


def fitness_SR(tag) -> float:
    return np.mean(math.mass(tag))


def fitness_entropy(tag) -> float:
    return np.sum(math.entropy(tag))
    
    
    
    
    
    